name: 同步sirpdboy-package
on:
  workflow_dispatch:

  schedule:
    - cron: 0 */6 * * *

jobs: 
  build:
    runs-on: Ubuntu-20.04
    name: 同步sirpdboy-package
    steps:
    - name: 重新拉取sirpdboy/sirpdboy-package仓库
      uses: danshui-git/github-forks-sync-action@main
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        upstream_repository: sirpdboy/sirpdboy-package
        upstream_branch: main
        target_repository: YWWei1988/sirpdboy-package       #修改成你的帐号/仓库名字
        target_branch: main                                 #你仓库的分支
        force: true
        tags: false
